### ISSUE TITLE
Verbosity in the VIS API

### ISSUE THREAD

**Issue by mikewinters** [ELVIS-Project/vis-framework#243]
Running the VIS API does not give any user feedback on the states of the code.  For example:

wm = WorkflowManager('../Beethoven String Quartet #1.mid')
wm.load('pieces')
wm.run('intervals')
wm.export('CSV','output_filename')

Leaves me hanging for a few minutes without telling me what's happening.  

I would suggest a verbosity 'switch' that the user can turn on or off, but which causes VIS to systematically post what it is doing.  This is done with a global control in the MIRToolbox, and it works great!

**Comment by alexandermorgan** [comment]
Motion to close... I don't think we need this.

**Comment by crantila** [comment]
Closed in favour of #357, which seems more suitable for the framework's goals today.
