### ISSUE TITLE
Additional "Get Started Quickly" Material

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#248]
This would be for people who want to use the VIS framework's existing modules. Our API's tutorials are intended for people who want to write new modules.

**Comment by alexandermorgan** [comment]
@slhowes , do you think this issue has already been addressed with the new documentation?

**Comment by slhowes** [comment]
Yes. The goal of the new documentation is definitely to "get started quickly" and it is intended for users who have little or no familiarity with VIS (and even Python). If #380 has been closed, I think this issue should be closed too.
