### ISSUE TITLE
Handle Predictable Errors

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#266]
There exists a series of errors we can predict people will encounter. We should either document the exceptions as they will be raised, do exception-chaining, or solve the problem where possible.

I'll add errors to the list as they occur to me:
- [x] invalid selection of voice combinations
- [x] problem running the R script
- [ ] problem getting the HTML output for either a table or chart
- [ ] music21 won't import a piece

**Comment by crantila** [comment]
@mrbannon Of the goals listed above, only "music21 won't import a piece" seems like a significant concern any more. The idea with this issue is that there would be ways to help prevent a single error from causing a whole analysis to fail... what happens if music21-via-Rodan fails to import a piece? Will other pieces still be analyzed? Will the user know it failed?

**Comment by mrbannon** [comment]
YES! The other pieces will be analyzed, and Rodan will inform the user.

**Comment by crantila** [comment]
This doesn't seem relevant any more. Closing.
