### ISSUE TITLE
Revive Chord N-Grams

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#271]
As in the ``ChordsLists`` experiment in vis9d (refer to [this thing](https://github.com/ELVIS-Project/vis/blob/vis9d/controllers/experimenter.py#L443)).

It's n-grams of named chords, as in: ``Am C#A Am`` for "A minor chord, C-sharp augmented chord, A minor chord."

We may also wish to "join" the chords with neo-Riemannian transformations or similar.

**Comment by musicus** [comment]
:neckbeard:

**Comment by crantila** [comment]
If nobody's mentioned it still, let's just close this and not say anything.

**Comment by musicus** [comment]
:-)
