### ISSUE TITLE
WorkflowManager.load() for Many Types

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#282]
We should allow importing previous results with the ``load()`` method. At minimum, this should be HDF5 and pickle. It must be clear that this won't load the metadata, and that the ``WorkflowManager`` will not make sure you're loading results that correspond to the pieces. But we should check, if the results are piece-by-piece, that they have the right number of pieces.

While we're at it, make ``'pieces'`` the default instruction.

**Comment by alexandermorgan** [comment]
The workflow manager has been deprecated and the importation of pieces has been overhauled so this part of the workflow manager is unlikely to still work. More generally, a thorough revision of the importation process is in order, especially with respect to how metafiles are parsed and aligned with pieces. This should be a separate issue though.
