### ISSUE TITLE
Use Slotted Classes for Settings

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#293]
As it turns out, Jamie was right: slotted objects are a much more efficient way to store settings than a dict. I'll still want to allow ``__init__()`` methods to accept a dict of settings, but we'll store it in a slotted object.

**Comment by alexandermorgan** [comment]
I didn't know about slotted classes so this was interesting to read about. It's a neat optimization but given the relatively low number of class instantiations that our queries generate this is probably not worth it unless ram really becomes an issue. Even then, as I understood it this would replace the default dictionary created when a class is instantiated, not its settings dictionary.

**Comment by crantila** [comment]
The idea was to use the object's dict instead of another one stored internally, but you're right that this is basically useless. The fun thing it allows is an immediate error when you mistype the name of a setting, which happens/happend to me *all the time*.
