### ISSUE TITLE
Persistent Results-Caching

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#295]
Our "model" objects should cache results (and metadata) between sessions. For this, this will involve local storage only, preferably of HDF5 files.

Some notes:
- we can use a SQLite database to store the metadata and pathnames of HDF5 results
- a file's sha256 checksum can be its key in the database (can music21 fetch this for us?)
- when the WorkflowManager.load('pieces') is called, it'll first check the database to see whether results are cached, and only load the piece through music21 if they're not
- I don't yet know how to manage analyzer settings
- when we get a list of analyzers, and we don't have the results for the whole list, we can check backward to see if we've cached intermediate results (i.e., somebody asks for [notes, intervals, frequency] and we don't have it, but maybe we have [notes, intervals]).

**Comment by maxalbert** [comment]
I have no idea about the context of this issue, so my comment probably won't be of any help (or won't even make sense), but the title reminded me of the `joblib.Memory` class: https://pythonhosted.org/joblib/memory.html  which I've been using quite a lot recently to cache results of computations to disk. Just thought I'd mention it in case it can be useful. If not, please ignore. :)

**Comment by crantila** [comment]
Thanks for this reference. I don't know whether this issue is still interesting for the current development team or their priorities. Personally, I'm going to investigate the ``joblib`` program for other uses.

To be honest, I doubt this feature will be implemented in the near future unless it's pathetically easy. At the moment, VIS just doesn't take long enough to warrant this type of caching.

**Comment by alexandermorgan** [comment]
While this issue is still far from resolved, it is important to note that the new architecture of VIS 3 (already present in alex_devel) makes extensive use of non-persistent caching. For deterministic  indexers or indexers whose output can be cajoled into some "complete" format that is easy to reindex, these results get cached for the duration of the existence of the indexed_piece object to which they are associated.

**Comment by crantila** [comment]
I'm closing this issue beacuse it isn't very important for RODAN-based VIS workflows, and nobody else seems interested.
