### ISSUE TITLE
LillyPond output occasionally provides incomplete score.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#306]
Requesting an annotated score of a 4-part Agnus Dei by Josquin (2-gram analysis on an xml file) only displayed the lower three voices. All six lines of expected analysis output were, however, correctly inserted below each system.

**Comment by musicus** [comment]
Same question as in #307, etc.

**Comment by musicus** [comment]
Closing issue as per #307.
