### ISSUE TITLE
No annotated score output for string quartets.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#307]
When requesting annotated score output of 2-gram analysis with an offset interval of 1, the terminal returned the error message below. This file was the first movement of Haydn's op 50 no. 1 (link to movement page in ELVIS database: http://elvis.music.mcgill.ca/node/1529 ) but other string quartet files also didn't work. All the string quartet files I tried were midi files.

>>> workm.output('LilyPond')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vis/workflow.py", line 657, in output
    return self._make_lilypond(pathname)
  File "vis/workflow.py", line 729, in _make_lilypond
    [self._result[i][j]])[0])
  File "vis/models/indexed_piece.py", line 395, in get_data
    return self.get_data(analyzer_cls[1:], settings, analyzer_cls[0](data, settings).run())
  File "vis/models/indexed_piece.py", line 395, in get_data
    return self.get_data(analyzer_cls[1:], settings, analyzer_cls[0](data, settings).run())
  File "vis/analyzers/indexers/lilypond.py", line 235, in __init__
    super(AnnotateTheNoteIndexer, self).__init__(score, None)
  File "vis/analyzers/indexer.py", line 229, in __init__
    raise TypeError(msg)
TypeError: <class 'vis.analyzers.indexers.lilypond.AnnotateTheNoteIndexer'> requires <class 'pandas.core.series.Series'> objects, not <class 'pandas.core.frame.DataFrame'>

**Comment by musicus** [comment]
Will this issue still be relevant once LilyPond has been deprecated?

**Comment by crantila** [comment]
This issue and #306 are both reports against the wrong software. No matter what happens to the LilyPond functionality in VIS, these two issues can probably be closed.

**Comment by musicus** [comment]
Ok, closing.
