### ISSUE TITLE
Better Handling of Piece-Specific/Aggregated Results in WorkflowManager

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#314]
The WorkflowManager has a setting to avoid running the frequency and aggregation experimenters. As far as I'm aware, this is only used to allow piece-specific results caching for LilyPond output. For sure, the LilyPond output requires piece-specific results, but there are (at least) two significant downsides to the current implementation strategy:
* choosing to avoid the frequency and aggregation expiermenters is only useful for LilyPond output, but screws up everything else, and
* the ability to choose LilyPond output depends on a setting that seems unrelated.

Why can't output('LilyPond') automatically choose the proper settings for itself? Why can't we output piece-specific spreadsheets? For that matter, why can't we have piece-specific caching that would allow for piece-specific score or spreadsheet output?

Well we can! We just have to program it.

**Comment by alexandermorgan** [comment]
Now that outputlilypond has been removed and the workflow manager has been deprecated this issue is no longer pertinent. Note that one of the larger points raised here, piece-specific caching, was implemented with the 3.0 release.
