### ISSUE TITLE
LilyPond Automatically Deletes Input Files

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#315]
LilyPond includes a commandline option to delete its input file. For the Web server, where .ly source files are nearly always a single-use affair, we should help the clean-up efforts by deleting those source files automatically.

**Comment by musicus** [comment]
Will this still be an issue once LilyPond had been deprecated?

**Comment by crantila** [comment]
For LilyPond, no. But it leads to asking the larger question about how intermediate files are handled when outputting from VIS. Maybe you won't have stray LilyPond files any more, but what about MusicXML?

**Comment by alexandermorgan** [comment]
The question of how we manage stored data is still an important one, even if we have now removed LilyPond. If we want to address the files that are produced by the RBarChart or Dendrogram experimenters, I think we can start with a fresh issue.
