### ISSUE TITLE
Think about How to Export Settings

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#316]
Team effort! If we're going to export settings in a way that breaks backward compatibility, we should do it now... so we don't have to force VIS 3 sooner than needed.

**Comment by alexandermorgan** [comment]
It looks like we're not going to export settings for VIS 3.0. Instead we're going to cache stable results that don't get influenced by settings. Post-processing indexers (like the n-gram indexer) will just get rerun every single time. There are simply too many possibilities to store them all in an orderly way. The good news is that most of these post-processing indexers are very fast to the point where they can probably be executed about as fast as users can choose the settings they want.
One intermediary case is interval indexing. In VIS 3.0 we will store the compound versions of intervals with quality and direction and with horiz_attach_later set to True for horizontal intervals. This type of analyses allow for zero information loss and can then be quickly reindexed with the IntervalReindexer to get the results to whatever format the user wants.
