### ISSUE TITLE
Incomplete continuous n-gram annotations

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#318]
When using the "Continuous LilyPond" output format, n-grams that are followed by events that aren't n-grams (most often these are rests in one of the parts) lack an annotation for their second vertical interval. In the picture below the rest in the upper part on the downbeat of m. 3 causes the third 2-gram in m. 2 to lack an annotation for it's second vertical interval. The second measure's annotations should end with 6 -2 7 but the seven is missing.
![lassus7](https://cloud.githubusercontent.com/assets/2601689/3906930/556f8f2e-22f7-11e4-9325-94f8a3e4c8c0.gif)

**Comment by alexandermorgan** [comment]
Didn't you already fix this @crantila ?

**Comment by crantila** [comment]
I think I only ended up fixing it in the "continuous_lilypond" branch.

**Comment by alexandermorgan** [comment]
These are now possible by using the new_ngram indexer with the 'hanging' setting set to True.

**Comment by musicus** [comment]
Will this still be an issue once LilyPond is deprecated?

**Comment by crantila** [comment]
Looks like @alexandermorgan solved the problem in January anyway?

**Comment by musicus** [comment]
Let's close it!
