### ISSUE TITLE
Without offset filter interval analysis is not truly in two voices.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#320]
When analyzing music with 3 or more voices and without an offset filter, if voices 1 and 2 are being analyzed, a note event in voice 3 seems to force an event in the analysis of voices 1 and 2 even at times when neither voice 1 nor voice 2 have events.

**Comment by crantila** [comment]
I can't quite remember what we decided to do about this?

**Comment by alexandermorgan** [comment]
This was sorted out by not using the 'ffill' setting when calculating dissonances. I guess I forgot to close the issue when I worked out dissonance detection. Thanks for digging this up.
