### ISSUE TITLE
Experimenter method to learn its class name

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#322]
Just as the Indexer superclass has a way to find its name (module plus class), the Experimenter superclass should provide this functionality for its subclasses.

**Comment by alexandermorgan** [comment]
I think that the indexers should actually abandon the module part of their names (in the dataframe columns anyway) because this creates a pandas syntax naming collision. See #394

**Comment by crantila** [comment]
I'm abandoning this because nobody cares.
