### ISSUE TITLE
Lilypond version requirements

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#339]
Lilypond doesn't seem to feature on any of the "requirements" or "optional requirements" lists though it is currently needed for score output. A Lilypond version a number (probably 2.18.2) and a website (http://www.lilypond.org/download.html) should be cited somewhere since it's not available through pip install.

**Comment by crantila** [comment]
Well-spotted, thanks for reporting this. I actually started writing the "you have to install LilyPond" bit for the API documentation revisions on the "devel_docs" branch... but it's still on my computer and I haven't even committed it yet. So I'll get on that.
