### ISSUE TITLE
Download URL on PyPI with link to tarball for latest version 2.1.1 does not work

### ISSUE THREAD

**Issue by maxalbert** [ELVIS-Project/vis-framework#341]
PyPI lists the following link to the tarball of the latest version:

Download URL: https://pypi.python.org/packages/source/v/vis-framework/vis-framework-2.1.1.tar.bz2

Unfortunately, this link seems to be dead. (I get redirected to a page with an XML error. The message tag reads: "The specified key does not exist".)

**Comment by crantila** [comment]
Maybe this is because @mrbannon 's GPG key isn't put somewhere that PyPI knows about it? Or did you sign the release, Ryan?

**Comment by mrbannon** [comment]
My apologies for not doing this earlier and getting to it so late.
