### ISSUE TITLE
VIS requires music21>=2.0.3, which is only available "implicitly" in git master

### ISSUE THREAD

**Issue by maxalbert** [ELVIS-Project/vis-framework#342]
The PyPI page lists `music21 (>=2.0.3, <2.1)` as a requirement. However, the latest released version of music21 is 2.0.0. In addition, no later version is explicitly tagged in the git repository. Therefore the only way of ensuring a recent enough version is to install music21 from git master, which is a bit flaky.

Not sure what to do about this. Maybe it could be mentioned in the installation instructions until a new version of music21 is released?

Update: I realised that the file `vis/requirements.txt` actually lists an explicit git commit. It might be good to mention this a bit more visibly, though.

**Comment by mrbannon** [comment]
I will address this on Monday.

Regarding music21, you can get the latest from their github page. As for
outputlilypond, it's not required for core use.

**Comment by maxalbert** [comment]
Ok, thanks! I did actually install music21 from git, but it took me a few attempts to find the correct combination of versions and the correct links for them (see my recent email to the music21 mailing list). For someone who isn't that familiar with pip or git this may be a big stumbling block. Re outputlilypond, if it isn't required for core use I guess it would be nice to have a slightly more graceful failure (as it's not apparent to the user whether it's needed or not, and "error" sounds like the installation process failed).

**Comment by mrbannon** [comment]
Fixed in v2.1.2
