### ISSUE TITLE
Check that indexers are respecting the 'simple or compound' setting

### ISSUE THREAD

**Issue by mrbannon** [ELVIS-Project/vis-framework#349]
I don't believe they are...

**Comment by alexandermorgan** [comment]
There are tests for all the different settings permutations, so this would surprise me if it's really the case.

**Comment by alexandermorgan** [comment]
I did horizontal, vertical, and ngram indexer analyses on a piece testing all four combinations of the 'quality' and the 'simple or compound' settings. All of them worked as expected for me so I'm closing this issue but feel free to show me next week what it is that made you think that these settings aren't working.
