### ISSUE TITLE
Scipy is needed for dendograms but I seem to lack the permission to install it in my virtual env on the server.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#350]
Here's what I tried to run on the server and the message I got. Scipy was downloaded but not installed:

sudo pip install scipy
The directory '/home/amor/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

and with the -H flag:

sudo -H pip install scipy

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-RzKIX7/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OioVan-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-RzKIX7/scipy

**Comment by ahankinson** [comment]
You do not need sudo to install on your virtual environment since you should have access to it through your user. Using sudo actually pops you out of your virtual environment, installing it in the system Python directory.

**Comment by alexandermorgan** [comment]
I guess I forgot to mention that I tried it without sudo first and that didn't work either.

**Comment by ahankinson** [comment]
What are the permissions on `'/home/amor/.cache/pip/http`? I'm guessing the permissions got screwed up there.

**Comment by alexandermorgan** [comment]
It's 700, (i.e. (rwx------) The file's owner may read, write, and execute the file. Nobody else has any rights.) what is it supposed to be?

**Comment by ahankinson** [comment]
Who's the file's owner? Are all the permissions in the sub-folders also assigned to the owner?

**Comment by alexandermorgan** [comment]
I am the owner of the file and the permissions in the sub-folders also seem to be assigned to me.

**Comment by ahankinson** [comment]
Then `pip install scipy` (without sudo) will work. You do not need sudo to install in your virtualenv.

Notice that it's executing with `/usr/bin/python`; if it was executing with your virtualenv it would be `/home/amor/path/to/virtualenv/bin/python`.

**Comment by alexandermorgan** [comment]
I'm not sure what Ryan did but it resolved this issue.
