### ISSUE TITLE
Compiling analyses of different pieces into a list of dataframes without aggregating their results into one undifferentiated dataframe.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#351]
Is there a way to run the same indexer on several pieces and keep the results together in one place (say a list of dataframes) but distinct in that the results of each piece's analysis are not combined with the others. I think this is the type of thing that you would feed to the aggregator experiment, but I don't want to aggregate the results. It would be straight forward enough to just code up on my own, but if it already exists in the framework it would definitely be better to go with that.
Is this already in the vis-framework? If not I'll get to work on it.
("Documentation" isn't really an appropriate label here, but it seems like the best option.)

**Comment by crantila** [comment]
Your issue titles are ridiculous!

The simple answer is "don't run an Experimenter."

There's already a setting for this in the [WorkflowManager](https://vis-framework.readthedocs.org/en/latest/modules.html#vis.workflow.WorkflowManager.settings), called "count_frequency." I admit that's not an obvious name when you're thinking "I don't want to aggregate," but it makes sense when considering that its original purpose was "I don't want to count the frequency."

Is this good enough? Or is there a different use case where a ``PleaseDontAggregateExperimenter`` is a better solution?

**Comment by alexandermorgan** [comment]
Ridiculous indeed! Thanks, I knew it was in there somewhere. I hadn't thought of this since I haven't been using the workflowmanager lately.
