### ISSUE TITLE
Magic mock objects incompatible with pandas.concat() in new make_return method in indexer.py

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#353]
The fact that the magic mock objects can't be concatenated causes two tests to fail (the old make_return() didn't use pandas.concat) so they have been turned off. They were testing the correct application of settings though, so this is unrelated to this issue with mock objects and pandas.concat(). Perhaps there's a simpler way to test that a setting has been correctly set. The tests are test_run_1 and test_run_2 in test_offset.py.

**Comment by crantila** [comment]
NB: the changes in question have already been merged into the master branch (commit 40cfe7435e70af5b8e57eb8e72c6b18b65230da0). Seems like you're doing this in the wrong order, especially considering that the Travis-CI builds on master have already been failing for months.

The tests are [here](https://github.com/ELVIS-Project/vis-framework/blob/b29378afb20434b0c439f63e778ad48d561a97b7/vis/tests/test_offset.py#L82) and [here](https://github.com/ELVIS-Project/vis-framework/blob/b29378afb20434b0c439f63e778ad48d561a97b7/vis/tests/test_offset.py#L91).

I'm not totally sure yet, but I think we don't need these tests. If the "method" isn't being set properly, we'll probably end up discovering that in one of the other tests. I want to double-check that before closing this issue, though.

**Comment by alexandermorgan** [comment]
Also, about the order of pushing stuff... note taken for the future. Though in this case it was intentional since the issue with these two tests is unrelated to my push and using the mock library, while really interesting, seems to complicated for me to maintain.

**Comment by alexandermorgan** [comment]
Erased tests replaced with commits fd2c18701fcbe1bd02e75e60a78bd5eba1fe1730 and 7776b187cf21a43655d0644e78ce95ce9747881f . New tests are still required to handle upbeat measures as noted in issue #356 but this issue is closed.
