### ISSUE TITLE
Provide option for combining positive and negative intervals in interval indexers.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#361]
There are currently settings to allow for analysis with or without interval quality and with simple or compound intervals, but a new setting is needed to provide absolute intervals (referred to as "canonical" intervals in other closed issues pertaining to the n-gram indexer). This would combine, for example, P4s and -P4s, meaning that the count would not be effected by which voice is on top. While less pressing, this may be a desirable setting to add tot he horizontal interval indexer too. These must be user-controllable settings because different queries will require different settings. The default should be kept as it is, where uncrossed and crossed versions of intervals are counted separately.

**Comment by alexandermorgan** [comment]
This looks like a good opportunity to simply how settings are passed to the interval indexer's "real_indexer_func".

**Comment by mrbannon** [comment]
Could you please put this in the vis-rodan github? It's not a client issue
but a wrapper issue. Tx.

**Comment by crantila** [comment]
VIS used to have this capability, but I don't think it ever made it into the Framework era. Not sure what Ryan means&mdash;this definitely seems like a setting for the ``IntervalIndexer``.

**Comment by alexandermorgan** [comment]
I agree that this should be in VIS itself because this will change the way the indexer_func in interval.py will work.
