### ISSUE TITLE
Plot directly from pandas using matplotlib.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#363]
We should plot directly from out data structures whenever possible using matplotlib and the functions described [here](http://pandas.pydata.org/pandas-docs/stable/visualization.html). I'm thinking of bar charts, histograms, and pie charts in particular, but many other plot types are possible too.
This would have the advantage of eliminating our optional requirement of R and consolidating our visual outputs by using matplotlib in the 'ggplot' style. Optional settings like changing the colors, titles, axis-labels, etc. would be easier to handle because they would be the same as those currently used for our dendrograms.
This should also be accompanied by a discussion about whether we only aim to produce raw data or whether we are generally interested in rendering that data for our users when it's very easy for us to do so. I think we should provide basic visualizations whenever possible because this is likely to make our framework much more useful to our average user. I don't think that we should bend over backwards to diversify or improve our existing visual outputs, but using matplotlib more extensively would require very little work on our part.

**Comment by ahankinson** [comment]
You should define who your users will be before you figure out what they need. As far as I can see, the bulk of the users who use vis will be those who use it through a web interface, and for that purpose having vis only produce data would be preferable to creating a primarily desktop oriented system.

**Comment by alexandermorgan** [comment]
We can use matplotlib to create pdf or png files which we could then send to a web user so I don't see how this is related to the question web vs. desktop orientation.

**Comment by ahankinson** [comment]
You would want to produce data for rendering by packages like D3.js (http://d3js.org), rather than just generating static images.

**Comment by alexandermorgan** [comment]
This was a decent idea but @ahankinson 's idea of using d3js is the direction we're taking and Andrew Fogarty is making good progress integrating that library with the VISualizer.
