### ISSUE TITLE
Add piece and part ranges to metadata about a piece.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#368]
Making piece and part ranges generally available in the metadata about a piece would be really useful for a number of analyses. Note that to do this it is probably best to use music21's analyze() method that you can run on streams. For example (taken from music21 documentation [here](http://web.mit.edu/music21/doc/moduleReference/moduleStream.html?highlight=stream#module-music21.stream)):
    >>> s = corpus.parse('bach/bwv66.6')
    >>> s.analyze('ambitus')
    \<music21.interval.Interval m21\>

This should probably go in indexed_piece.py.

**Comment by mborsodi** [comment]
Added to my branch
