### ISSUE TITLE
Simple way of loading all files in a given directory.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#369]
This used to exist with the workflow manager I believe but if we still have it I haven't been able to find it anywhere. This should be a part of the core framework. Perhaps it should be a method in indexed_piece.py.

**Comment by musicus** [comment]
yes...that's why i started on something else ...

**Comment by alexandermorgan** [comment]
@musicus , why was this issue reassigned to me when you've already been working on it?

**Comment by musicus** [comment]
?

**Comment by musicus** [comment]
Closing the issue. The feature, along with reading files directly from the ELVIS database will be part of the VIS-Aardvark extension.

**Comment by musicus** [comment]
Closing the issue. The feature, along with reading files directly from the ELVIS database will be part of the VIS-Aardvark extension.

**Comment by alexandermorgan** [comment]
I still don't see why this would be in an extension since importing files is core functionality. Also this issue should stay open until the fix is available in the master branch.

**Comment by musicus** [comment]
Perhaps. In that case build it. I'll continue to use my own.

**Comment by mborsodi** [comment]
Alright, I added this functionality to aggregated pieces. It now takes:
- a list of indexed pieces (as before)
- a list of files (new)
- a path to a folder from which it can also extract the meta data if present (new)
- a list of links (new)

Also for all the options above you can now also add metadata as an input option as well.

Now, I'm working on adding something that can parse through larger json files and extract all the music and metadata from that (but that has more to do with issue #138 than this one). Aggregated pieces should work the same as it did before, but with some added flexibility.
