### ISSUE TITLE
metre.py

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#378]
The module should really be re-named _meter.py_, since by programming convention American English is preferred (rather than British English).

**Comment by mborsodi** [comment]
Is [this](https://github.com/ELVIS-Project/vis-framework/commit/356c16b88fae58d6707824ce61efc856b85825a5) what you mean or is there more to it?

**Comment by alexandermorgan** [comment]
Great, though we'll still have to change metre to meter in all of the tests.

**Comment by crantila** [comment]
You can't say "okay this is finished except for the proof that it works" and close the issue...

**Comment by mborsodi** [comment]
Done

**Comment by musicus** [comment]
:smile_cat:
