### ISSUE TITLE
metre.py Documentation

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#379]
The _metre.py_ module is not showing up in the [automated documentation](http://vis-framework.readthedocs.org/en/latest/) module section, nor in the [API specification](http://vis-framework.readthedocs.org/en/latest/index.html). It is cumbersome having to look at the source code's doc strings, or the tests as only sources of documentation.

**Comment by crantila** [comment]
Good catch. If you add it to [vis.analyzers.indexers.rst](https://raw.githubusercontent.com/ELVIS-Project/vis-framework/master/doc/api/vis.analyzers.indexers.rst) it should build just fine.

**Comment by musicus** [comment]
Ha - Sweet!

**Comment by musicus** [comment]
Added.
