### ISSUE TITLE
Contour Indexer

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#385]
It would be great to a contour indexer for motivic fragments. The output should be a dataframe (, or the export output of the dataframe to JSON).

**Comment by mborsodi** [comment]
How would you suggest this work in terms of getting the contour/s of an entire piece? Should there be a "length" setting or something to look at that length of fragments?

**Comment by musicus** [comment]
Windowing motives, and specifying how long a motive should be. A motive should be at least 3 notes long, and at the longest should include all the notes of a line. However, the shorter motives may yield the higher amount of self-similar contour types.

**Comment by mborsodi** [comment]
Added in my branch

**Comment by musicus** [comment]
Awesome! I'll check it out later!
