### ISSUE TITLE
Build is failing in Python 2.7.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#389]
@musicus your last commit caused the build to fail in python 2.7. Please don't commit directly to master in the future, even if it's a mostly cosmetic commit like it was yesterday.

**Comment by alexandermorgan** [comment]
Also, it's called the new_ngram indexer, not the new_gram indexer.

**Comment by musicus** [comment]
I updated static files ... Travis hypothetically shouldn't fail, but will follow procedure next time.

**Comment by ahankinson** [comment]
I suspect the build failing was caused by gremlins, since it looked like it failed when installing scipy. :japanese_ogre: I restarted the build to see if it persists.

**Comment by musicus** [comment]
Where is that spelling error?

**Comment by ahankinson** [comment]
Looks like it's passing now.

**Comment by alexandermorgan** [comment]
Great. new_gram was just in your commit message.
