### ISSUE TITLE
Active voices indexer

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#391]
We need an indexer to tell us how many voices are active (not resting) at any given time. I guess the output format would be a 1 column dataframe of integers showing how many voices are active at every new event in the cumulative offsets of all the voices. If we wanted to get fancy we could convey when this changes, because you could easily have a constant number of active voices but with a changing combination of voices. In other words one voice could drop out at the moment that another one comes in and we may want to find some way to convey this information too despite the fact that the number of active voices would be constant.

**Comment by crantila** [comment]
Good idea! This would be a great task for a new contributor!

**Comment by mborsodi** [comment]
Just to clarify, active includes voices that are on held notes, right? Basically any sounding voice?

**Comment by alexandermorgan** [comment]
@mborsodi yes, held voices would still be considered active. That being said, your question makes the case for an attack_indexer, but let's wait until someone actually has a query that would make use of the number of attacks for that one. I haven't even started this in case you're interested in doing it.

**Comment by mborsodi** [comment]
I wonder if "attacked" could just be setting that defaults to show held notes.. I'd be happy to do it, it doesn't seem like too big a project.

**Comment by alexandermorgan** [comment]
Good idea about the attack setting!

**Comment by musicus** [comment]
👍
