### ISSUE TITLE
Corpus class for handling queries on more than one piece

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#393]
Make a new class of corpus objects which will basically be a list of indexed pieces. Running regular analyzers on this list will execute that analysis on each piece in the list and return a list of the resulting dataframes (instead of just one dataframe as is usually the case with analyzer results. The Rodan client may have it's own solution to this problem, but even if it does running analyses on more than one piece in one go is core functionality for analysis software and the user shouldn't have to write a loop for every query that involves more than one piece. This won't be a proper workflow manager. It'll mostly just be a simple set of convenience methods. FYI @mrbannon

**Comment by musicus** [comment]
This functionality is in VIS-for-Pd. There should be a tool that can merge DataFrames so that corpus studies are still possible.

**Comment by alexandermorgan** [comment]
The best way I've found to merge dataframes is with the following command:
`pandas.concat([list of dataframes])
`
It returns the passed dataframes merged into one dataframe.

**Comment by musicus** [comment]
Exactly!

**Comment by crantila** [comment]
What about [AggregatedPieces](https://github.com/ELVIS-Project/vis-framework/blob/master/vis/models/aggregated_pieces.py#L36)?

**Comment by alexandermorgan** [comment]
@crantila , thank you. Not thinking of aggregatedpieces was an oversight on my part. This even has some functionality (like the meta-metadata) that I hadn't even thought of. It looks great but I'm having trouble using it. It's a little tough to figure out since all the examples are abstract and the tests all use mock objects. Do you have a script that uses it in any way?

**Comment by crantila** [comment]
There `_run_freq_agg()`[ in the WorkflowManager](https://github.com/ELVIS-Project/vis-framework/blob/master/vis/workflow.py#L670).

I'm not going to try convincing anyone that the documentation and test suite are particularly good, but AggregatedPieces is designed to be as close to IndexedPiece as possible.

**Comment by alexandermorgan** [comment]
Thanks Christopher, this link helps a lot!

**Comment by alexandermorgan** [comment]
Closing because aggregated_pieces is already in the framework and working and Marina even recently made some improvements to it.
