### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#397]
Create an installer so VIS can be installed not just with pip, i.e.: click this file, and it installs.

**Comment by mrbannon** [comment]
Is there anything you recommend to facilitate this?

**Comment by crantila** [comment]
Once you [Ansible](https://docs.ansible.com/ansible/index.html), you don't go back!

**Comment by musicus** [comment]
That is a possibility, for example.

**Comment by alexandermorgan** [comment]
Who is going to do this? In case anybody was thinking of me, I'm really not the person for this task.

**Comment by musicus** [comment]
Ok. I'll assign it to @mborsodi.

**Comment by musicus** [comment]
😸
