### ISSUE TITLE
Pandas documentation

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#399]
Provide, additional pandas documentation in regards to music theory/musicology use cases.

**Comment by mborsodi** [comment]
To be added:

- concatenating
- indexing by part and by offset
- creating new dataframes (?)
- map and applymap examples
- Alex's cross-referencing filter technique

What am I missing?

**Comment by musicus** [comment]
Yes (especially the difference between ```map``` and ```applymap```)!

Here are some more basic items I use all the time:

- Extracting one (a single part/voice) series from a DataFrame
- Describe: ```.describe()```
- Instant Histograms: ```.value_counts()```
- Most counted value: ```.mode()```
- Get all values in a series as an array: ```.values```
- Amount of events in a series: ```.size```

We should go through the pandas documentation bit by bit to see what pandas features can be useful (non-useful ones we leave out), so we have all of our bases covered.

**Comment by mborsodi** [comment]
Thanks! @alexandermorgan do you have any more suggestions to add?

**Comment by alexandermorgan** [comment]
Yes, I would point out that `.value_counts()` only works on a series. If you want to flatten one of our multi-indexed dataframes into a series and then count those events, you can do this `noterestDF.stack().stack().value_counts()`
To just get the index of a dataframe: `df.index`
Just the columns: `df.columns` though this one is a little more complex given our multi-index
If you want to do index-based selection of a column in a dataframe, you can do this: `df.iloc[:, column_number]`
Label-based is a little trickier given our multi-indexed columns, but it still works if you pass a tuple with the label for each level of the multi-index: `df.loc[:, ('noterest.NoteRestIndexer', '2')]`
Getting a row is the same syntax: `df.iloc[index_number_of_row, :]`
Slicing also works in the regular python way: `df.iloc[3:, :]`
Figuring out all the places a certain value is found is also valuable, but I can't think of the "where" syntax at the moment. It's something like `numpy.where...`
One of the most useful things is how to filter. To get the durations of the notes and filter out those of the rests: `durationsDF[noterestDF != 'Rest']`
I think that's enough to get people going.

**Comment by alexandermorgan** [comment]
Also, if you're going to distinguish between applymap and map, you should probably explain apply too, and this in the context of series and dataframes because I'm pretty sure they're different (applymap is only for dataframes). But those are pretty complex functions, I'm not sure you would want to venture into all that for a little intro to pandas.

**Comment by musicus** [comment]
@alexandermorgan - yes, now we are getting somewhere...

**Comment by mborsodi** [comment]
What's the benefit of using ```.value_counts()``` over the frequency experiment that we have in VIS? Don't they do the same thing?

**Comment by musicus** [comment]
Yes, it appears to be similar. However, for documentation purposes it should be mentioned. You should test and compare the performance. Again, as I stated before _we should go through the pandas documentation bit by bit_. Any _jargon_ should be avoided, and anything should be stated as clearly as possible.

**Comment by musicus** [comment]
The use of ```apply```, ```applymap``` (specifically for pandas & Python), and ```map```, or the use of similar higher-order functions is very common in other programming languages ... so I do not see a reason why not to venture there. We want to have the most complete documentation as possible, from basic to cookbook ...

**Comment by musicus** [comment]
@mborsodi you finished your part, but the issue needs to stay open.

**Comment by alexandermorgan** [comment]
For anyone who's looking, Marina's pandas documentation is [here](https://github.com/ELVIS-Project/vis-framework/wiki/Pandas).

**Comment by musicnerd** [comment]
Hi guys, as someone working my way through the pandas documentation I had a few comments: 1) there are 2 broken links at the top of the page: "One step beyond" (which in the text body is actually called "one step further" and the one underneath that, "Advanced pandas" which doesn't actually seem to have made it into the body at all, so perhaps it needs to be deleted?  Also I can see you guys talking about subjects such as .value_counts() but I don't see that anywhere in the documentation. Am I missing something?

**Comment by mborsodi** [comment]
You can go ahead and change the broken links,  I might have changed some of the organization of the text along the way and forgotten to change the index at the beginning.
Value counts is something that we do in VIS called the frequency experimenter. I left it out of the pandas documentation here because of that. Having an experimenter doing something that a pandas function can do might be a separate issue though.

**Comment by musicus** [comment]
@musicnerd - I fixed the 2 broken links on the top, but you are more then welcome to fix anything else in the documentation as well ... ```.value_counts()``` is a part of [pandas](http://pandas.pydata.org/pandas-docs/version/0.16.2/generated/pandas.Series.value_counts.html).

Here is more pandas documentation (as long as your pandas is pandas>=0.14.1,<0.17, I added this to the pandas section of the wiki as well): 
- [10 minutes to pandas](http://pandas.pydata.org/pandas-docs/version/0.16.2/10min.html)
- [Tutorials](http://pandas.pydata.org/pandas-docs/version/0.16.2/tutorials.html)
- [Cookbook](http://pandas.pydata.org/pandas-docs/version/0.16.2/cookbook.html)

**Comment by musicnerd** [comment]
Marina: In the section of the wiki under "concatenating" you paste the line of code that you need to cat the two dataframes together. But then, you show two dataframes (notes and intervals) aligned by the same index (or "pasted" together) but you don't show the line of code used to generate that.  Could you either add it or just reply here and I can add it?  That seems useful.

**Comment by mborsodi** [comment]
Sorry about that @musicnerd. The code is almost exactly the same:
`pandas.concat([df1, df2], axis=1)`
