### ISSUE TITLE
New Dissonance Indexer

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#409]
Even though I fundamentally disagree with the proposed new dissonance indexer, may I request to still include the old dissonance indexer in the 3.0 release, perhaps it could be prefixed with ```old_```, and should be marked as being deprecated.

**Comment by alexandermorgan** [comment]
I'm not sure I know what you're talking about. I never proposed a new dissonance indexer.

**Comment by musicus** [comment]
Whatever you proposed at the ELVIS meeting on Friday, I thought it was a re-write of the dissonance indexer, but maybe something else, I don't have my notes on me. In either case I would like to propose the same procedure as outlined above.

**Comment by alexandermorgan** [comment]
Since there aren't two versions of the dissonance indexer I can't deprecate one in favor of a second one that doesn't exist. We can discuss this in person if you like but I'm closing this issue since there's nothing to do.

**Comment by musicus** [comment]
Until we discuss this issue in person it will remain open.
