### ISSUE TITLE
test_aggregated_pieces.TestAggregatedPieces failing.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#414]
test_run3, test_run4, and test_run6 in test_aggregated_pieces.TestAggregatedPieces are failing in the develop branch. @mborsodi , could you look into these? There are a couple of other tests that are also failing, but I can take care of those, I've just never really worked with the code of aggregatedPieces so this is a little tough for me to sort through.

**Comment by alexandermorgan** [comment]
Now this passes on alex_devel. The reason it wasn't passing before is that I didn't have the hidden file .DS_store in vis/tests/corpus/elvisdownload because I guess hidden files don't come through with a standard git merge. We'll have to make sure this file goes into master too when we release VIS 3.0.

**Comment by crantila** [comment]
No! `.DS_store` files are macOS system files. It's really not okay that a test requires an OS-specific cache, and very irresponsible git usage on the part of whoever committed that file.

**Comment by alexandermorgan** [comment]
@crantila wow, ok thanks for the heads-up!

**Comment by alexandermorgan** [comment]
This wasn't as bad as it might have seemed. In the actual code of aggregated_pieces, the DS_Store file is only removed if it's there. This same check is now done in the tests.
