### ISSUE TITLE
There are at least two types of NaN's.

### ISSUE THREAD

**Issue by alexandermorgan** [ELVIS-Project/vis-framework#426]
There seems to be a general float nan and a numpy float nan, and they are not equivalent. This is complicating our checks for nans which are common since they are the default N/A value. For now I'm working around this problem, but eventually VIS needs a good systematic solution for this.

**Comment by musicus** [comment]
... and this bug is in the new release as well?

**Comment by alexandermorgan** [comment]
A bug was perhaps not the best label, I'll admit. This is more of just the way things work with numpy/pandas. I made this issue just for it to be on people's radar. I'll go ahead and close it though.
