### ISSUE TITLE
cadence indexer Documentation

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#430]
This object is not being properly picked up by sphinx, nor is its documentation in the docstring.

The code example that is part of the docstring needs to look the following way in the [```run()``` method](https://github.com/ELVIS-Project/vis-framework/blob/master/vis/analyzers/indexers/cadence.py#L86):
```
***Examples***
 
>>> import music21
>>> import pandas
>>> import vis.analyzers.indexers import noterest, interval, over_bass, fermata, cadence
 
>>> score = music21.converter.parse('example.xml')
>>> notes = noterest.NoteRestIndexer(score).run()
>>> intervals = interval.IntervalIndexer(notes).run()
 
>>> fermatas = fermata.FermataIndexer(score).run()
 
>>> df = pandas.concat([notes, intervals])
>>> overbass = over_bass.OverBassIndexer(df).run()
 
>>> settings = {'length': 3}
>>> df = pandas.concat([overbass, fermatas])
 
>>> cadences = cadence.CadenceIndexer(df, settings).run()
>>> print(cadences)

```

The docstring should also feature some prose describing what is being done, and why it is important. There also needs to be an example of the desired outcome of when the exact code is being run, with an ```example.xml``` form the ```vis/tests/corpus/``` directory.

**Comment by alexandermorgan** [comment]
Why would you assign this to me when I didn't even write this indexer?

**Comment by musicus** [comment]
You are the project lead until you leave, and I asked to make sure that all documentation works and shows up via sphinx in the API porperly.

**Comment by musicus** [comment]
Docstrings aligned with Sphinx, and code brought into pep8 compliance (mostly).
