### ISSUE TITLE
contour indexer Documentation

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#431]
This object is not being picked up by sphinx.

What are contours? What type of contours? Contours according to whom? There should be prose in the docstring that describes these items.

The code examples in the ```run()``` method need to look the following way:

```
>>> import music21
>>> from vis.analyzers.indexers import noterest, contour 

>>> score = music21.converter.parse('example.xml')
>>> notes = noterest.NoteRestIndexer(score).run()
 
>>> settings = {'length': 3}
>>> contours = contour.ContourIndexer(notes).run()
>>> print(contours)
```

There should also be prose on what this code does, and what its expected outcome would look like.

**Comment by alexandermorgan** [comment]
Seriously, no more assigning things to me, especially when I didn't write them.

**Comment by musicus** [comment]
Hey, your name is on the release ... and the documentation that is not being picked up by sphinx is part of that release. I just now have time to look at all the code in detail. I apologize. I'm mostly making notes for the future.

**Comment by musicus** [comment]
Docstrings aligned with Sphinx, and code brought into pep8 compliance (mostly).
