### ISSUE TITLE
Find Invertible Counterpoint

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#55]
Depends on Issue #43.

We should be able to find occurrences of "invertible at the ___" n-grams, then mark them on the LilyPond score. This is useful, for instance, for the **8 +4 5 1 8 -3 10 1 8 +4 5** *stretto fuga* 6-gram and its "at the 12th" inversion at the end of the Kyrie for Palestrina's "Missa Pro Defunctis."

**Comment by alexandermorgan** [comment]
Update: I worked this out about a year ago but it's still just a loose script.

**Comment by crantila** [comment]
Could you please upload that to the ``vis/scripts`` directory and put a link in this issue? And maybe write a comment in that file with the commit hash of the latest git commit it works with. Then we can probably close this issue.

**Comment by alexandermorgan** [comment]
It's probably the first script I ever wrote but ok. I put it on the alex_devel branch with commit 42f68a94948e63c2b9836a55c2c392f3539314e2.
